AWSTemplateFormatVersion: 2010-09-09
Description: EGI-Demo EC2 Demo-0.0.0.1
Parameters:
  ImageID:
    Description: 'AWS Amazon Machine Image ID'
    Type: String
    Default: 'ami-0bdef2eb518663879' #AMI ID for ubuntu 18.04 in AWS region us-west-2, Comprehensive list: https://cloud-images.ubuntu.com/locator/ec2/
  VpcCIDRBlock:
    Description: 'CIDR Block for VPC Ex.10.0.0.0/16'
    Type: String
    Default: 10.0.0.0/16
  SubnetCIDRBlock:
    Description: 'CIDR Block for public subnet Ex.10.0.1.0/24'
    Type: String
    Default: 10.0.41.0/24
Resources:
  VPC:
    Type: AWS::EC2::VPC
    DeletionPolicy: Retain
    Properties:
      CidrBlock: !Ref 'VpcCIDRBlock'
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: DemoVPC 
  DemoSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: DemoSG
      VpcId: !Ref VPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: '0.0.0.0/0'
      - IpProtocol: icmpv6
        FromPort: -1
        ToPort: -1       
        CidrIp: '0.0.0.0/0'
  DemoSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      VpcId: 
        Ref: VPC
      CidrBlock: !Ref 'SubnetCIDRBlock'
      Tags:
        - Key: Name
          Value: DemoSubnet
  DemoBastionInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: 'DemoKey'
      ImageId: !Ref ImageID
      InstanceType: t2.micro
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - Ref: DemoSG
          SubnetId: 
            Ref: "DemoSubnet"
      UserData:
        Fn::Base64: !Sub |
                   #!/bin/bash
                   wget https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb -O /tmp/amazon-cloudwatch-agent.deb
                   dpkg -i /tmp/amazon-cloudwatch-agent.deb
                   apt-get update -y
                   apt-get  install -y python-pip
                   easy_install --script-dir /opt/aws/bin  https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
                   /opt/aws/bin/cfn-init -v --stack ${AWS::StackId} --resource EC2Instance --region ${AWS::Region} --configsets default
                   /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource EC2Instance --region ${AWS::Region}      
      Tags:
        - Key: Name
          Value: DemoBastionInstance
