# This GitHub Actions workflow to deploy service on AWS using a manual trigger
name: DeployOnAWS

on:
  workflow_dispatch:
    inputs:
      applicationName:
        description: 'AWS Deploy application-name Parameter'     
        required: true
        default: timeofuseEndpoint
      deploymentGroupName:
        description: 'AWS Deploy deployment-group-name Parameter'     
        required: true
        default: timeofuseEndpoint
      s3Bucket:
        description: 'S3 bucket name'     
        required: true
        default: gobuilds
      buildZipName:
        description: 'Build zip file name'     
        required: true
        default: servicec.zip
jobs:       
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            persist-credentials: false
            fetch-depth: 0
      
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
            aws-region: us-east-2

        - name: Trigger CodeDeploy
          id: deploy
          run: |
            # Assuming the Deployment Group is already setup
            aws deploy create-deployment \
            --application-name ${{ github.event.inputs.applicationName }} \
            --deployment-group-name ${{ github.event.inputs.deploymentGroupName }} \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --ignore-application-stop-failures \
            --s3-location bucket=${{ github.event.inputs.s3Bucket }},key=${{ github.event.inputs.buildZipName }},bundleType=zip