# This GitHub Actions workflow gets trigger on a push event on develop branch with a version tag
name: RunTests
on:
  push:
    tags:
        - 'test-*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-latest, ubuntu-18.04]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v2
        with:
            go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests in tests
        ## Change directory as applicable
        run: go test -v -covermode=count