ARG TB_VERSION

# https://www.docker.elastic.co/
FROM thingsboard/tb-postgres:${TB_VERSION}

# Thingsboard with Postgres db backend
# Thingsboard with Cassandra or Hybrid installation can also be found at hub.docker.com